### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Andrew813** [reva-ture/lendr#2]
![goldmanstax](https://user-images.githubusercontent.com/9217906/37250153-ffd01c1e-24c3-11e8-877c-e2c1cb396cb5.png)

**Comment by Andrew813** [comment]
![gstax](https://user-images.githubusercontent.com/9217906/37255377-127c0c02-2522-11e8-900f-84a339c1ae97.png)

**Comment by Andrew813** [comment]
![lendr1](https://user-images.githubusercontent.com/9217906/37255802-14061486-2528-11e8-8f93-63c3c2aacd01.png)

**Comment by Andrew813** [comment]
![lendr2](https://user-images.githubusercontent.com/9217906/37255848-c7458766-2528-11e8-9762-a0d9bf189273.png)

**Comment by Andrew813** [comment]
![lendr3](https://user-images.githubusercontent.com/9217906/37255966-b6796702-252a-11e8-8aca-f36b4cf02d0c.png)

**Comment by Andrew813** [comment]
![lendr4](https://user-images.githubusercontent.com/9217906/37257108-e9ce26b4-253a-11e8-9626-80e7df0c14bc.png)

**Comment by Andrew813** [comment]
![lendr4](https://user-images.githubusercontent.com/9217906/37257116-0f84bcce-253b-11e8-9010-86be76b3ef63.png)

**Comment by Andrew813** [comment]
![lendr4](https://user-images.githubusercontent.com/9217906/37257131-3c34c5b6-253b-11e8-96a5-95964b01a333.png)

**Comment by Andrew813** [comment]
![lendr5](https://user-images.githubusercontent.com/9217906/37257188-08ea8bc2-253c-11e8-9c36-aa74cd7a2b50.png)

**Comment by Andrew813** [comment]
![lendrp2p1](https://user-images.githubusercontent.com/9217906/37318190-88dfd914-263f-11e8-832a-061e4930b839.png)

**Comment by Andrew813** [comment]
![lendr23](https://user-images.githubusercontent.com/9217906/37318387-92db4a9c-2640-11e8-8258-fb2095bb9ab4.png)

**Comment by Andrew813** [comment]
![lendrd](https://user-images.githubusercontent.com/9217906/37318864-0bf64b78-2643-11e8-9992-de7116a3445a.png)

**Comment by Andrew813** [comment]
![lendrd](https://user-images.githubusercontent.com/9217906/37318929-4261f3d8-2643-11e8-9921-b1ba3421b1e6.png)

**Comment by Andrew813** [comment]
![lendrdd](https://user-images.githubusercontent.com/9217906/37318970-75f59a24-2643-11e8-8d0c-ff8877c2f6be.png)

**Comment by Andrew813** [comment]
![lendrddd](https://user-images.githubusercontent.com/9217906/37319213-92f12a7a-2644-11e8-8e8b-97f5dfa35b4f.png)

**Comment by Andrew813** [comment]
![lendr22222](https://user-images.githubusercontent.com/9217906/37319491-a60e0e7e-2645-11e8-917f-2d0362384554.png)

**Comment by Andrew813** [comment]
![lender](https://user-images.githubusercontent.com/9217906/37319547-e9ca7b66-2645-11e8-9faa-3f1e310fb308.png)

**Comment by Andrew813** [comment]
![lendrv1](https://user-images.githubusercontent.com/9217906/37320630-fd7ae7fe-264a-11e8-91cb-ff7a65053977.png)

**Comment by Andrew813** [comment]
![lendrv2](https://user-images.githubusercontent.com/9217906/37320730-6e328cf4-264b-11e8-8754-f42b576eea48.png)

**Comment by Andrew813** [comment]
![lendrda](https://user-images.githubusercontent.com/9217906/37320840-035acb5c-264c-11e8-9454-e67e201173ce.png)

**Comment by Andrew813** [comment]
![lendrc](https://user-images.githubusercontent.com/9217906/37320951-9575f3fe-264c-11e8-8f4f-9e0ec5397eb2.png)

**Comment by hall** [comment]
It would be good to have one such that the logo could be used as a favicon.ico.

**Comment by Andrew813** [comment]
Noted. Will brainstorm.

**Comment by Andrew813** [comment]
![lendrfav](https://user-images.githubusercontent.com/9217906/37741070-746900ac-2d36-11e8-9238-4fb0ccdb51be.png)

**Comment by Andrew813** [comment]
![lendrfav2](https://user-images.githubusercontent.com/9217906/37741243-08d53b66-2d37-11e8-9f02-2cb5ac83a3a9.png)
