### ISSUE TITLE
We need a name

### ISSUE THREAD

**Issue by hall** [reva-ture/lendr#3]
Leave one comment for each name and we can vote on the ones we like.

**Comment by hall** [comment]
lendr

**Comment by hall** [comment]
Goldman Stax

**Comment by hall** [comment]
My problem with Goldman Stax is the baggage of being affiliated with Goldman Sachs -- especially since they don't have a stellar reputation.

**Comment by Andrew813** [comment]
We can always call our group Goldman Stax, and our product can still be Lendr.

**Comment by aloryde** [comment]
lendr

**Comment by Andrew813** [comment]
![lendrc](https://user-images.githubusercontent.com/9217906/37320938-8833001a-264c-11e8-84ca-f9591cafd2fb.png)
